(cl:in-package k2_client-msg)
(cl:export '(HEADER-VAL
          HEADER
          LEANTRACKINGSTATE-VAL
          LEANTRACKINGSTATE
          LEAN-VAL
          LEAN
          ISRESTRICTED-VAL
          ISRESTRICTED
          TRACKINGID-VAL
          TRACKINGID
          CLIPPEDEDGES-VAL
          CLIPPEDEDGES
          HANDRIGHTCONFIDENCE-VAL
          HANDRIGHTCONFIDENCE
          HANDRIGHTSTATE-VAL
          HANDRIGHTSTATE
          HANDLEFTCONFIDENCE-VAL
          HANDLEFTCONFIDENCE
          HANDLEFTSTATE-VAL
          HANDLEFTSTATE
          JOINTORIENTATIONS-VAL
          JOINTORIENTATIONS
          JOINTPOSITIONS-VAL
          JOINTPOSITIONS
))